package sentinel;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.io.InputStream;
import java.lang.reflect.Method;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;

@DisplayName("Loader Agent and Bytecode Transformation Tests")
class LoaderTest {

    private Loader loader;

    @BeforeEach
    void setUp() {
        loader = new Loader();
    }

    @Test
    @DisplayName("Null safety: transform returns null for null or empty inputs")
    void testNullAndEmptyInputs() {
        assertNull(loader.transform(null, null, null, null, null));
        assertNull(loader.transform(null, "demo/target/TargetService", null, null, null));
        assertNull(loader.transform(null, "demo/target/TargetService", null, null, new byte[0]));
    }

    @Test
    @DisplayName("Scope gating: transform returns null for unrelated classes")
    void testUnrelatedClassesIgnored() {
        byte[] dummyBytecode = new byte[]{1, 2, 3};
        assertNull(loader.transform(null, "java/lang/String", null, null, dummyBytecode));
        assertNull(loader.transform(null, "sentinel/Loader", null, null, dummyBytecode));
        assertNull(loader.transform(null, "sentinel/Filter", null, null, dummyBytecode));
        assertNull(loader.transform(null, "demo/app/DemoApplication", null, null, dummyBytecode));
        assertNull(loader.transform(null, "com/example/RandomService", null, null, dummyBytecode));
    }

    @Test
    @DisplayName("Target transformation: successfully modifies message() while preserving add()")
    void testTargetServiceTransformation() throws Exception {
        byte[] originalBytecode = loadTargetServiceBytecode();
        assertNotNull(originalBytecode, "Could not locate TargetService.class resource");

        // Execute transformation
        byte[] transformedBytecode = loader.transform(
                getClass().getClassLoader(),
                "demo/target/TargetService",
                null,
                null,
                originalBytecode
        );

        assertNotNull(transformedBytecode, "Transformed bytecode should not be null");

        // Load the transformed bytecode into an isolated child-first ClassLoader
        ByteArrayClassLoader customLoader = new ByteArrayClassLoader(
                getClass().getClassLoader(),
                "demo.target.TargetService",
                transformedBytecode
        );

        Class<?> transformedClass = customLoader.loadClass("demo.target.TargetService");
        Object instance = transformedClass.getDeclaredConstructor().newInstance();

        // Verify message() was modified
        Method messageMethod = transformedClass.getMethod("message");
        Object messageResult = messageMethod.invoke(instance);
        assertEquals("Transformed message", messageResult, "message() must return 'Transformed message'");

        // Verify add() was preserved unchanged
        Method addMethod = transformedClass.getMethod("add", int.class, int.class);
        Object addResult = addMethod.invoke(instance, 15, 25);
        assertEquals(40, addResult, "add() must retain original logic and return 40");
    }

    @Test
    @DisplayName("Idempotency: retransforming an already instrumented class returns null")
    void testIdempotentRetransformation() throws Exception {
        byte[] originalBytecode = loadTargetServiceBytecode();
        assertNotNull(originalBytecode);

        // First transformation
        byte[] firstPass = loader.transform(
                getClass().getClassLoader(),
                "demo/target/TargetService",
                null,
                null,
                originalBytecode
        );
        assertNotNull(firstPass, "First transformation must succeed");

        // Second transformation on the same bytecode (retransformation scenario)
        byte[] secondPass = loader.transform(
                getClass().getClassLoader(),
                "demo/target/TargetService",
                null,
                null,
                firstPass
        );

        assertNull(secondPass, "Subsequent transformation must detect existing instrumentation and return null");
    }

    private byte[] loadTargetServiceBytecode() throws IOException {
        String resourcePath = "demo/target/TargetService.class";
        try (InputStream in = getClass().getClassLoader().getResourceAsStream(resourcePath)) {
            if (in == null) {
                return null;
            }
            return in.readAllBytes();
        }
    }

    /**
     * Isolated child-first ClassLoader to load and verify generated bytecode at runtime.
     */
    private static class ByteArrayClassLoader extends ClassLoader {
        private final String targetClassName;
        private final byte[] classBytes;

        ByteArrayClassLoader(ClassLoader parent, String targetClassName, byte[] classBytes) {
            super(parent);
            this.targetClassName = targetClassName;
            this.classBytes = classBytes;
        }

        @Override
        public Class<?> loadClass(String name, boolean resolve) throws ClassNotFoundException {
            if (targetClassName.equals(name)) {
                Class<?> c = findLoadedClass(name);
                if (c == null) {
                    c = findClass(name);
                }
                if (resolve) {
                    resolveClass(c);
                }
                return c;
            }
            return super.loadClass(name, resolve);
        }

        @Override
        protected Class<?> findClass(String name) throws ClassNotFoundException {
            if (targetClassName.equals(name)) {
                return defineClass(name, classBytes, 0, classBytes.length);
            }
            return super.findClass(name);
        }
    }
}
